version: '3'

services:
# Database
  db:
    image: mariadb:10 # need to add build .
    container_name: mariadb
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - wpsite
# phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
    networks:
      - wpsite
# Wordpress
  wordpress:
    depends_on:
      - db
    image: wordpress:php7.3-fpm-alpine # need to add build .
    container_name: wordpress
    ports:
      - '9000:80'
    restart: always
    volumes:
      - wp_html:/var/www/html
    environment:
      MYSQL_ROOT_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    networks:
      - wpsite
  nginx:
    depends_on:
      - wordpress
    build: ./requirements/nginx/
    container_name: nginx
    volumes:
      - wp_html:/www
    ports:
      - 443:443
    links:
      - wordpress
    restart: always
    networks:
      - wpsite

# Network setup
networks:
  wpsite:
# Volumes setup
volumes:
  db_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./requirements/mariadb/data
  wp_html:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./requirements/wordpress/html


# sudo docker-compose down --rmi all --> stop all and delete all images
