version: '3'

services:
# phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - '8080:80'
    # environment:
    #   PMA_HOST: db
    #   MYSQL_ROOT_PASSWORD: password
    networks:
      - wpsite
    env_file:
      - .env

# Database
  db:
    build: ./requirements/mariadb/
    image: mariadb
    container_name: mariadb
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    # environment:
    #   MYSQL_ROOT: root
    #   MYSQL_ROOT_PASSWORD: password
    #   MYSQL_DATABASE: wordpress
    #   MYSQL_USER: wordpressdock
    #   MYSQL_PASSWORD: password
    networks:
      - wpsite
    env_file:
      - .env

# Wordpress
  wordpress:
    depends_on:
      - db
    # image: wordpress:php7.3-fpm-alpine # need to add build .
    image: wordpress
    build: ./requirements/wordpress/
    container_name: wordpress
    restart: always
    volumes:
      - wp_html:/var/www/html
    # environment:
      # MYSQL_ROOT_PASSWORD: password
      # WORDPRESS_DB_NAME: wordpress
      # WORDPRESS_DB_HOST: db
      # WORDPRESS_DB_USER: wordpress
      # WORDPRESS_DB_PASSWORD: password
      # WORDPRESS_TABLE_PREFIX: wp_
    env_file:
      - .env
    networks:
      - wpsite

# nginx
  nginx:
    build: ./requirements/nginx/
    image: nginx
    container_name: nginx
    volumes:
      - wp_html:/var/www/html
    ports:
      - 443:443
    restart: always
    env_file:
      - .env
    networks:
      - wpsite

# Network setup
networks:
  wpsite:

# Volumes setup
volumes:
  db_data:
    name: db_data
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/afaraji/data/db_data

  wp_html:
    name: wp_html
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/afaraji/data/wp_data


# sudo docker-compose down --rmi all --> stop all and delete all images
