version: '3'

services:
# phpmyadmin
  # phpmyadmin:
  #   depends_on:
  #     - db
  #   image: phpmyadmin/phpmyadmin
  #   container_name: phpmyadmin
  #   restart: always
  #   ports:
  #     - '8880:80'
  #   # environment:
  #   #   PMA_HOST: db
  #   #   MYSQL_ROOT_PASSWORD: password
  #   networks:
  #     - wpsite
  #   env_file:
  #     - .env

# Database
  db:
    build: ./requirements/mariadb/
    image: mariadb
    container_name: mariadb
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    # environment:
    #   MYSQL_ROOT: root
    #   MYSQL_ROOT_PASSWORD: password
    #   MYSQL_DATABASE: wordpress
    #   MYSQL_USER: wordpressdock
    #   MYSQL_PASSWORD: password
    networks:
      - wpsite
    env_file:
      - .env

# Wordpress
  wordpress:
    depends_on:
      - db
    # image: wordpress:php7.3-fpm-alpine # need to add build .
    image: wordpress
    build: ./requirements/wordpress/
    container_name: wordpress
    restart: always
    volumes:
      - wp_html:/var/www/html
    # environment:
      # MYSQL_ROOT_PASSWORD: password
      # WORDPRESS_DB_NAME: wordpress
      # WORDPRESS_DB_HOST: db
      # WORDPRESS_DB_USER: wordpress
      # WORDPRESS_DB_PASSWORD: password
      # WORDPRESS_TABLE_PREFIX: wp_
    env_file:
      - .env
    networks:
      - wpsite

# nginx
  nginx:
    build: ./requirements/nginx/
    image: nginx
    container_name: nginx
    depends_on:
      - wordpress
    volumes:
      - wp_html:/var/www/html
    ports:
      - 443:443
    restart: always
    env_file:
      - .env
    networks:
      - wpsite

# redis
  redis:
    build: ./requirements/bonus/redis/
    image: redis
    container_name: redis
    depends_on:
      - wordpress
    ports:
      - 6379:6379
    restart: always
    env_file:
      - .env
    networks:
      - wpsite
# adminer
  adminer:
    build: ./requirements/bonus/adminer/
    image: adminer
    container_name: adminer
    depends_on:
      - db
    ports:
      - 8080:8080
    restart: always
    env_file:
      - .env
    networks:
      - wpsite

# ftp-server
  ftp:
    build: ./requirements/bonus/ftp/
    image: ftp
    container_name: ftp
    depends_on:
      - wordpress
    ports:
      - "21:21"
      - "20:20"
      - "40000-40010:40000-40010"
    volumes:
      - wp_html:/var/www/html
    restart: always
    env_file:
      - .env
    networks:
      - wpsite

# website
  website:
    build: ./requirements/bonus/site/
    image: website
    container_name: website
    ports:
      - "1337:1337"
    # volumes:
    #   - wp_html:/var/www/html
    restart: always
    env_file:
      - .env
    networks:
      - wpsite

# cAdvisor
  cadvisor:
    build: ./requirements/bonus/cadvisor/
    image: cadvisor
    container_name: cadvisor
    ports:
    - 8081:8080
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    restart: always
    env_file:
      - .env
    networks:
      - wpsite

# Network setup
networks:
  wpsite:

# Volumes setup
volumes:
  db_data:
    name: db_data
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/afaraji/data/db_data

  wp_html:
    name: wp_html
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/afaraji/data/wp_data


# sudo docker-compose down --rmi all --> stop all and delete all images
