USE mysql;
FLUSH PRIVILEGES ;
GRANT ALL ON *.* TO 'root'@'%' identified by 'password' WITH GRANT OPTION ;
GRANT ALL ON *.* TO 'root'@'localhost' identified by 'password' WITH GRANT OPTION ;
SET PASSWORD FOR 'root'@'localhost'=PASSWORD('password') ;
DROP DATABASE IF EXISTS test ;
FLUSH PRIVILEGES ;
CREATE DATABASE IF NOT EXISTS `wordpress` CHARACTER SET utf8 COLLATE utf8_general_ci;
GRANT ALL ON `wordpress`.* to 'wordpress'@'%' IDENTIFIED BY 'password';
CREATE USER 'afaraji'@'%' IDENTIFIED BY 'password';
GRANT SELECT ON `wordpress`.* TO 'afaraji'@'%';
FLUSH PRIVILEGES;
